import React, { createContext, useContext, useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';

type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    home: 'Home',
    login: 'Login',
    signup: 'Sign Up',
    logout: 'Logout',
    
    // App
    'app.name': 'Clinlix',
    'app.tagline': 'Trusted Cleaning, Every Single Time',
    
    // Auth
    'auth.welcomeBack': 'Welcome Back',
    'auth.createAccount': 'Create Account',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.phone': 'Phone Number',
    'auth.phoneOptional': 'Phone (Optional)',
    'auth.iAmCustomer': "I'm a Customer",
    'auth.iAmProvider': "I'm a Service Provider",
    'auth.continueWithGoogle': 'Continue with Google',
    'auth.or': 'or',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.resetPassword': 'Reset Password',
    'auth.backToSignIn': 'Back to Sign In',
    'auth.sendResetLink': 'Send Reset Link',
    'auth.resetEmailSent': 'Password reset email sent! Check your inbox.',
    'auth.accountCreated': 'Account created successfully! Welcome!',
    'auth.signInSuccess': 'Welcome back!',
    'auth.signInError': 'Invalid email or password',
    'auth.passwordTooShort': 'Password must be at least 6 characters',
    'auth.passwordMismatch': 'Passwords do not match',
    'auth.allFieldsRequired': 'Please fill in all required fields',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.submit': 'Submit',
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Info',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.settings': 'Settings',
    'common.profile': 'Profile',
    'common.logout': 'Logout',
    'common.language': 'Language',
    'common.currency': 'Currency',
    'common.notifications': 'Notifications',
    'common.security': 'Security',
    'common.account': 'Account',
    'common.continue': 'Continue',
    'common.welcome': 'Welcome',
    'common.firstName': 'First Name',
    'common.lastName': 'Last Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.country': 'Country',
    'common.customer': 'Customer Account',
    'common.saving': 'Saving...',
    'common.saveChanges': 'Save Changes',
    'common.logoutSuccess': 'Logged out successfully',
    
    // Dashboard
    'dashboard.welcome': 'Welcome',
    'dashboard.myBookings': 'My Bookings',
    'dashboard.findProviders': 'Find Providers',
    'dashboard.myAddresses': 'My Addresses',
    'dashboard.paymentMethods': 'Payment Methods',
    'dashboard.settings': 'Settings',
    'dashboard.profile': 'Profile',
    'dashboard.upcomingBookings': 'Upcoming Bookings',
    'dashboard.noBookings': 'No bookings yet',
    'dashboard.startBooking': 'Start Booking',
    'dashboard.bookCleaning': 'Book a Cleaning',
    
    // Settings
    'settings.title': 'Settings',
    'settings.customerSettings': 'Customer Settings',
    'settings.providerSettings': 'Provider Settings',
    'settings.accountInfo': 'Account Information',
    'settings.accountDetails': 'Your basic account details',
    'settings.firstName': 'First Name',
    'settings.lastName': 'Last Name',
    'settings.phoneNumber': 'Phone Number',
    'settings.emailAddress': 'Email Address',
    'settings.emailCannotChange': 'Email cannot be changed',
    'settings.notifications': 'Notifications',
    'settings.notificationsDesc': 'Manage how you receive updates',
    'settings.pushNotifications': 'Push Notifications',
    'settings.pushNotificationsDesc': 'Receive real-time updates in your browser or app',
    'settings.emailNotifications': 'Email Notifications',
    'settings.emailNotificationsDesc': 'Receive booking updates via email',
    'settings.smsNotifications': 'SMS Notifications',
    'settings.smsNotificationsDesc': 'Receive booking updates via SMS',
    'settings.language': 'Language',
    'settings.languageDesc': 'Choose your preferred language',
    'settings.selectLanguage': 'Select language',
    'settings.currencyPreference': 'Currency Preference',
    'settings.currencyDesc': 'Based on your country selection',
    'settings.currencyAuto': 'Currency is automatically set based on your country',
    'settings.security': 'Security',
    'settings.securityDesc': 'Manage your account security',
    'settings.changePassword': 'Change Password',
    'settings.passwordResetInfo': "We'll send you an email with instructions to reset your password",
    'settings.changesSaved': '✅ Changes saved',
    'settings.failedToSave': 'Failed to save changes',
    'settings.failedToLoad': 'Failed to load settings',
    'settings.passwordResetSent': 'Password reset email sent! Check your inbox.',
    'settings.failedToSendReset': 'Failed to send reset email',
    'settings.pushEnabled': '✅ Push notifications enabled',
    'settings.pushDisabled': 'Push notifications disabled',
    'settings.countryCannotChange': 'Country cannot be changed',
    'settings.dangerZone': 'Danger Zone',
    
    // Provider
    'provider.availabilityPreferences': 'Availability Preferences',
    'provider.availabilityDesc': 'Manage your work preferences',
    'provider.acceptRecurring': 'Accept Recurring Clients',
    'provider.acceptRecurringDesc': 'Allow customers to book you regularly',
    'provider.currentlyAvailable': 'Currently Available',
    'provider.currentlyAvailableDesc': 'Show as available for new bookings',
    'provider.verification': 'Verification',
    'provider.verificationDesc': 'Boost your profile credibility',
    'provider.becomeVerified': 'Become Verified',
    'provider.verifiedInfo': 'Verified providers get more bookings and customer trust',
    'provider.languageRegion': 'Language & Region',
    'provider.myJobs': 'My Jobs',
    'provider.jobRequests': 'Job Requests',
    'provider.requests': 'Requests',
    'provider.confirmed': 'Confirmed',
    'provider.completed': 'Completed',
    'provider.dashboard': 'Dashboard',
    'provider.schedule': 'Schedule',
    'provider.wallet': 'Wallet',
    'provider.reviews': 'Reviews',
    'provider.available': 'Available',
    'provider.offline': 'Offline',
    'provider.earnings': 'Earnings',
    'provider.pending': 'Pending',
    'provider.paid': 'Paid',
    'provider.totalEarned': 'Total Earned',
    'provider.platformFee': 'Platform Fee',
    'provider.payoutDue': 'Payout Due',
    'provider.pendingJobs': 'Pending Jobs',
    'provider.availableJobs': 'Available Jobs',
    'provider.earnedThisMonth': 'Earned This Month',
    'provider.quickActions': 'Quick Actions',
    'provider.jobs': 'Jobs',
    'provider.viewAllJobs': 'View all jobs',
    'provider.manageAvailability': 'Manage availability',
    'provider.viewEarnings': 'View earnings',
    'provider.profile': 'Profile',
    'provider.editProfile': 'Edit profile',
    'provider.noPendingJobs': 'No pending job requests',
    'provider.noConfirmedJobs': 'No confirmed jobs',
    'provider.noCompletedJobs': 'No completed jobs yet',
    'provider.completeJobsToEarn': 'Complete jobs to start earning',
    'provider.basePrice': 'Base Price',
    'provider.addons': 'Add-ons',
    'provider.estimatedEarnings': 'Estimated Earnings',
    'provider.viewJobDetails': 'View Job Details',
    'provider.viewJob': 'View Job',
    'provider.earned': 'earned',
    'provider.viewSummary': 'View Summary',
    'provider.mySchedule': 'My Schedule',
    'provider.addEditSlots': 'Add or edit your available time slots',
    'provider.add': 'Add',
    'provider.next30Days': 'Next 30 Days',
    'provider.selectDateToManage': 'Select a date to manage availability',
    'provider.noAvailabilitySet': 'No availability set for this day',
    'provider.addAvailableSlots': 'Add your available time slots to receive bookings',
    'provider.addAvailability': 'Add Availability',
    'provider.slotAvailable': 'slot available',
    'provider.slotsAvailable': 'slots available',
    'provider.trackEarnings': 'Track your earnings',
    'provider.pendingPayout': 'Pending Payout',
    'provider.earningsHistory': 'Earnings History',
    'provider.viewAllTransactions': 'View all your transactions',
    'provider.all': 'All',
    'provider.noEarningsYet': 'No earnings yet',
    'provider.base': 'Base',
    'provider.fee': 'Fee',
    'provider.overtime': 'Overtime',
    'provider.customerFeedback': 'Customer feedback',
    'provider.basedOn': 'Based on',
    'provider.review': 'review',
    'provider.allReviews': 'All Reviews',
    'provider.noReviewsYet': 'No reviews yet',
    'provider.completeJobsForReviews': 'Complete jobs to receive customer reviews',
    'provider.providerSettings': 'Provider Settings',
    'provider.myProfile': 'My Profile',
    'provider.manageYourInfo': 'Manage your information',
    'provider.personalInformation': 'Personal Information',
    'provider.updateBasicDetails': 'Update your basic details',
    'provider.providerInformation': 'Provider Information',
    'provider.detailsAboutService': 'Details about your service',
    'provider.firstName': 'First Name',
    'provider.lastName': 'Last Name',
    'provider.phone': 'Phone',
    'provider.email': 'Email',
    'provider.country': 'Country',
    'provider.bio': 'Bio',
    'provider.tellCustomers': 'Tell customers about yourself...',
    'provider.yearsOfExperience': 'Years of Experience',
    'provider.skills': 'Skills',
    'provider.selectSkills': 'Select skills...',
    'provider.serviceAreas': 'Service Areas',
    'provider.selectAreas': 'Select service areas...',
    'provider.languages': 'Languages',
    'provider.selectLanguages': 'Select languages...',
    'provider.saveChanges': 'Save Changes',
    'provider.saving': 'Saving...',
    'provider.previewPublicProfile': 'Preview Public Profile',
    'provider.call': 'Call',
    'provider.jobDetails': 'Job Details',
    
    // Providers
    'providers.findProviders': 'Find Providers',
    'providers.searchProviders': 'Search providers...',
    'providers.noProvidersFound': 'No providers found yet',
    'providers.checkBackSoon': 'Check back soon as we onboard more cleaning professionals',
    'providers.viewProfile': 'View Profile',
    'providers.bookNow': 'Book Now',
    'providers.newBadge': 'NEW',
    'providers.verifiedBadge': 'VERIFIED',
    'providers.findNearYou': 'Find providers near you...',
    'providers.filterProviders': 'Filter Providers',
    'providers.narrowSearch': 'Narrow your search',
    'providers.verifiedOnly': 'Verified Only',
    'providers.showVerifiedOnly': 'Show only verified providers',
    'providers.minimumRating': 'Minimum Rating',
    'providers.whereNeedService': 'Where do you need service?',
    'providers.enterCity': 'Enter your city',
    'providers.checkAvailability': 'Check Availability',
    'providers.filterByDate': 'Filter by availability on a specific date',
    'providers.resetFilters': 'Reset Filters',
    'providers.activeFilters': 'Active filters:',
    'providers.verified': 'Verified',
    'providers.stars': 'stars',
    'providers.area': 'Area:',
    'providers.date': 'Date:',
    'providers.noMatches': 'No matches yet',
    'providers.tryDifferentFilters': 'Try different filters or expand your search area',
    'providers.providersAvailable': 'providers available',
    'providers.provider': 'provider',
    
    // Addresses
    'addresses.myAddresses': 'My Addresses',
    'addresses.manageAddresses': 'Manage up to 5 addresses',
    'addresses.addAddress': 'Add Address',
    'addresses.editAddress': 'Edit Address',
    'addresses.addNewAddress': 'Add New Address',
    'addresses.addressLabel': 'Address Label',
    'addresses.labelPlaceholder': 'Home, Office, etc.',
    'addresses.firstName': 'First Name',
    'addresses.lastName': 'Last Name',
    'addresses.phone': 'Phone',
    'addresses.email': 'Email',
    'addresses.country': 'Country',
    'addresses.propertyType': 'Property Type',
    'addresses.apartment': 'Apartment',
    'addresses.house': 'House',
    'addresses.layoutType': 'Layout Type',
    'addresses.studio': 'Studio',
    'addresses.oneBedroom': '1 Bedroom',
    'addresses.twoBedrooms': '2 Bedrooms',
    'addresses.threeBedrooms': '3 Bedrooms',
    'addresses.fourBedrooms': '4 Bedrooms',
    'addresses.rua': 'Rua',
    'addresses.codigoPostal': 'Código Postal',
    'addresses.portaAndar': 'Porta/Andar',
    'addresses.localidade': 'Localidade',
    'addresses.distrito': 'Distrito',
    'addresses.streetAddress': 'Street Address',
    'addresses.aptUnit': 'Apt/Unit',
    'addresses.postalCode': 'Postal Code',
    'addresses.city': 'City',
    'addresses.province': 'Province',
    'addresses.setPrimary': 'Set as primary address',
    'addresses.updateAddress': 'Update Address',
    'addresses.saveAddress': 'Save Address',
    'addresses.noAddresses': 'No addresses saved yet',
    'addresses.addFirstAddress': 'Add Your First Address',
    'addresses.primary': 'Primary',
    'addresses.deleteAddress': 'Delete',
    'addresses.maxAddresses': 'Maximum 5 addresses allowed',
    'addresses.addressAdded': 'Address added successfully',
    'addresses.addressUpdated': 'Address updated successfully',
    'addresses.addressDeleted': 'Address deleted',
    'addresses.failedToLoad': 'Failed to load addresses',
    'addresses.failedToSave': 'Failed to save address',
    'addresses.failedToDelete': 'Failed to delete address',
    'addresses.confirmDelete': 'Are you sure you want to delete this address?',
    
    // Bookings
    'bookings.myBookings': 'My Bookings',
    'bookings.active': 'Active',
    'bookings.completed': 'Completed',
    'bookings.cancelled': 'Cancelled',
    'bookings.viewDetails': 'View Details',
    'bookings.paid': 'Paid',
    'bookings.package': 'Package',
    'bookings.total': 'Total',
    'bookings.cancelBooking': 'Cancel Booking',
    'bookings.leaveReview': 'Leave a Review',
    'bookings.noCompleted': 'No completed bookings',
    'bookings.noCancelled': 'No cancelled bookings',
    'bookings.confirmCancel': 'Are you sure you want to cancel this booking?',
    'bookings.bookingCancelled': 'Booking cancelled',
    'bookings.failedToCancel': 'Failed to cancel booking',
    'bookings.failedToLoad': 'Failed to load bookings',
  },
  pt: {
    // Navigation
    home: 'Início',
    login: 'Entrar',
    signup: 'Registar',
    logout: 'Sair',
    
    // App
    'app.name': 'Clinlix',
    'app.tagline': 'Limpeza de confiança, todas as vezes',
    
    // Auth
    'auth.welcomeBack': 'Bem-vindo de Volta',
    'auth.createAccount': 'Criar Conta',
    'auth.signIn': 'Entrar',
    'auth.signUp': 'Registar',
    'auth.email': 'Email',
    'auth.password': 'Palavra-passe',
    'auth.confirmPassword': 'Confirmar Palavra-passe',
    'auth.firstName': 'Primeiro Nome',
    'auth.lastName': 'Último Nome',
    'auth.phone': 'Número de Telefone',
    'auth.phoneOptional': 'Telefone (Opcional)',
    'auth.iAmCustomer': 'Sou Cliente',
    'auth.iAmProvider': 'Sou Prestador de Serviços',
    'auth.continueWithGoogle': 'Continuar com Google',
    'auth.or': 'ou',
    'auth.dontHaveAccount': 'Não tem conta?',
    'auth.alreadyHaveAccount': 'Já tem conta?',
    'auth.forgotPassword': 'Esqueceu a Palavra-passe?',
    'auth.resetPassword': 'Redefinir Palavra-passe',
    'auth.backToSignIn': 'Voltar ao Início de Sessão',
    'auth.sendResetLink': 'Enviar Link de Redefinição',
    'auth.resetEmailSent': 'Email de redefinição de palavra-passe enviado! Verifique a sua caixa de entrada.',
    'auth.accountCreated': 'Conta criada com sucesso! Bem-vindo!',
    'auth.signInSuccess': 'Bem-vindo de volta!',
    'auth.signInError': 'Email ou palavra-passe inválidos',
    'auth.passwordTooShort': 'A palavra-passe deve ter pelo menos 6 caracteres',
    'auth.passwordMismatch': 'As palavras-passe não coincidem',
    'auth.allFieldsRequired': 'Por favor, preencha todos os campos obrigatórios',
    
    // Common
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.close': 'Fechar',
    'common.back': 'Voltar',
    'common.next': 'Seguinte',
    'common.submit': 'Submeter',
    'common.search': 'Pesquisar',
    'common.loading': 'A carregar...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.warning': 'Aviso',
    'common.info': 'Informação',
    'common.confirm': 'Confirmar',
    'common.yes': 'Sim',
    'common.no': 'Não',
    'common.ok': 'OK',
    'common.settings': 'Definições',
    'common.profile': 'Perfil',
    'common.logout': 'Sair',
    'common.language': 'Idioma',
    'common.currency': 'Moeda',
    'common.notifications': 'Notificações',
    'common.security': 'Segurança',
    'common.account': 'Conta',
    'common.continue': 'Continuar',
    'common.welcome': 'Bem-vindo',
    'common.firstName': 'Primeiro Nome',
    'common.lastName': 'Último Nome',
    'common.email': 'Email',
    'common.phone': 'Telefone',
    'common.country': 'País',
    'common.customer': 'Conta de Cliente',
    'common.saving': 'A guardar...',
    'common.saveChanges': 'Guardar Alterações',
    'common.logoutSuccess': 'Sessão encerrada com sucesso',
    
    // Dashboard
    'dashboard.welcome': 'Bem-vindo',
    'dashboard.myBookings': 'As Minhas Reservas',
    'dashboard.findProviders': 'Encontrar Prestadores',
    'dashboard.myAddresses': 'As Minhas Moradas',
    'dashboard.paymentMethods': 'Métodos de Pagamento',
    'dashboard.settings': 'Definições',
    'dashboard.profile': 'Perfil',
    'dashboard.upcomingBookings': 'Reservas Futuras',
    'dashboard.noBookings': 'Ainda não tem reservas',
    'dashboard.startBooking': 'Iniciar Reserva',
    'dashboard.bookCleaning': 'Agendar Limpeza',
    
    // Settings
    'settings.title': 'Definições',
    'settings.customerSettings': 'Definições de Cliente',
    'settings.providerSettings': 'Definições de Prestador',
    'settings.accountInfo': 'Informação da Conta',
    'settings.accountDetails': 'Os seus dados básicos da conta',
    'settings.firstName': 'Primeiro Nome',
    'settings.lastName': 'Último Nome',
    'settings.phoneNumber': 'Número de Telefone',
    'settings.emailAddress': 'Endereço de Email',
    'settings.emailCannotChange': 'O email não pode ser alterado',
    'settings.notifications': 'Notificações',
    'settings.notificationsDesc': 'Gerir como recebe atualizações',
    'settings.pushNotifications': 'Notificações Push',
    'settings.pushNotificationsDesc': 'Receber atualizações em tempo real no navegador ou app',
    'settings.emailNotifications': 'Notificações por Email',
    'settings.emailNotificationsDesc': 'Receber atualizações de reservas por email',
    'settings.smsNotifications': 'Notificações SMS',
    'settings.smsNotificationsDesc': 'Receber atualizações de reservas por SMS',
    'settings.language': 'Idioma',
    'settings.languageDesc': 'Escolha o seu idioma preferido',
    'settings.selectLanguage': 'Selecionar idioma',
    'settings.currencyPreference': 'Preferência de Moeda',
    'settings.currencyDesc': 'Baseado na seleção do seu país',
    'settings.currencyAuto': 'A moeda é automaticamente definida com base no seu país',
    'settings.security': 'Segurança',
    'settings.securityDesc': 'Gerir a segurança da sua conta',
    'settings.changePassword': 'Alterar Palavra-passe',
    'settings.passwordResetInfo': 'Enviaremos um email com instruções para redefinir a sua palavra-passe',
    'settings.changesSaved': '✅ Alterações guardadas',
    'settings.failedToSave': 'Falha ao guardar alterações',
    'settings.failedToLoad': 'Falha ao carregar definições',
    'settings.passwordResetSent': 'Email de redefinição de palavra-passe enviado! Verifique a sua caixa de entrada.',
    'settings.failedToSendReset': 'Falha ao enviar email de redefinição',
    'settings.pushEnabled': '✅ Notificações push ativadas',
    'settings.pushDisabled': 'Notificações push desativadas',
    'settings.countryCannotChange': 'O país não pode ser alterado',
    'settings.dangerZone': 'Zona de Perigo',
    
    // Provider
    'provider.availabilityPreferences': 'Preferências de Disponibilidade',
    'provider.availabilityDesc': 'Gerir as suas preferências de trabalho',
    'provider.acceptRecurring': 'Aceitar Clientes Recorrentes',
    'provider.acceptRecurringDesc': 'Permitir que os clientes o reservem regularmente',
    'provider.currentlyAvailable': 'Atualmente Disponível',
    'provider.currentlyAvailableDesc': 'Mostrar como disponível para novas reservas',
    'provider.verification': 'Verificação',
    'provider.verificationDesc': 'Aumentar a credibilidade do seu perfil',
    'provider.becomeVerified': 'Tornar-se Verificado',
    'provider.verifiedInfo': 'Os prestadores verificados obtêm mais reservas e confiança dos clientes',
    'provider.languageRegion': 'Idioma e Região',
    'provider.myJobs': 'Os Meus Trabalhos',
    'provider.jobRequests': 'Pedidos de Trabalho',
    'provider.requests': 'Pedidos',
    'provider.confirmed': 'Confirmado',
    'provider.completed': 'Concluído',
    'provider.dashboard': 'Painel',
    'provider.schedule': 'Agenda',
    'provider.wallet': 'Carteira',
    'provider.reviews': 'Avaliações',
    'provider.available': 'Disponível',
    'provider.offline': 'Offline',
    'provider.earnings': 'Ganhos',
    'provider.pending': 'Pendente',
    'provider.paid': 'Pago',
    'provider.totalEarned': 'Total Ganho',
    'provider.platformFee': 'Taxa da Plataforma',
    'provider.payoutDue': 'Pagamento Devido',
    'provider.pendingJobs': 'Trabalhos Pendentes',
    'provider.availableJobs': 'Trabalhos Disponíveis',
    'provider.earnedThisMonth': 'Ganho Este Mês',
    'provider.quickActions': 'Ações Rápidas',
    'provider.jobs': 'Trabalhos',
    'provider.viewAllJobs': 'Ver todos os trabalhos',
    'provider.manageAvailability': 'Gerir disponibilidade',
    'provider.viewEarnings': 'Ver ganhos',
    'provider.profile': 'Perfil',
    'provider.editProfile': 'Editar perfil',
    'provider.noPendingJobs': 'Sem pedidos de trabalho pendentes',
    'provider.noConfirmedJobs': 'Sem trabalhos confirmados',
    'provider.noCompletedJobs': 'Ainda sem trabalhos concluídos',
    'provider.completeJobsToEarn': 'Conclua trabalhos para começar a ganhar',
    'provider.basePrice': 'Preço Base',
    'provider.addons': 'Extras',
    'provider.estimatedEarnings': 'Ganhos Estimados',
    'provider.viewJobDetails': 'Ver Detalhes do Trabalho',
    'provider.viewJob': 'Ver Trabalho',
    'provider.earned': 'ganho',
    'provider.viewSummary': 'Ver Resumo',
    'provider.mySchedule': 'A Minha Agenda',
    'provider.addEditSlots': 'Adicionar ou editar os seus horários disponíveis',
    'provider.add': 'Adicionar',
    'provider.next30Days': 'Próximos 30 Dias',
    'provider.selectDateToManage': 'Selecione uma data para gerir a disponibilidade',
    'provider.noAvailabilitySet': 'Sem disponibilidade definida para este dia',
    'provider.addAvailableSlots': 'Adicione os seus horários disponíveis para receber reservas',
    'provider.addAvailability': 'Adicionar Disponibilidade',
    'provider.slotAvailable': 'horário disponível',
    'provider.slotsAvailable': 'horários disponíveis',
    'provider.trackEarnings': 'Acompanhe os seus ganhos',
    'provider.pendingPayout': 'Pagamento Pendente',
    'provider.earningsHistory': 'Histórico de Ganhos',
    'provider.viewAllTransactions': 'Ver todas as suas transações',
    'provider.all': 'Todos',
    'provider.noEarningsYet': 'Ainda sem ganhos',
    'provider.base': 'Base',
    'provider.fee': 'Taxa',
    'provider.overtime': 'Horas Extras',
    'provider.customerFeedback': 'Feedback do Cliente',
    'provider.basedOn': 'Baseado em',
    'provider.review': 'avaliação',
    'provider.allReviews': 'Todas as Avaliações',
    'provider.noReviewsYet': 'Ainda sem avaliações',
    'provider.completeJobsForReviews': 'Conclua trabalhos para receber avaliações dos clientes',
    'provider.providerSettings': 'Definições de Prestador',
    'provider.myProfile': 'O Meu Perfil',
    'provider.manageYourInfo': 'Gerir a sua informação',
    'provider.personalInformation': 'Informação Pessoal',
    'provider.updateBasicDetails': 'Atualizar os seus dados básicos',
    'provider.providerInformation': 'Informação de Prestador',
    'provider.detailsAboutService': 'Detalhes sobre o seu serviço',
    'provider.firstName': 'Primeiro Nome',
    'provider.lastName': 'Último Nome',
    'provider.phone': 'Telefone',
    'provider.email': 'Email',
    'provider.country': 'País',
    'provider.bio': 'Biografia',
    'provider.tellCustomers': 'Fale aos clientes sobre si...',
    'provider.yearsOfExperience': 'Anos de Experiência',
    'provider.skills': 'Competências',
    'provider.selectSkills': 'Selecione competências...',
    'provider.serviceAreas': 'Áreas de Serviço',
    'provider.selectAreas': 'Selecione áreas de serviço...',
    'provider.languages': 'Idiomas',
    'provider.selectLanguages': 'Selecione idiomas...',
    'provider.saveChanges': 'Guardar Alterações',
    'provider.saving': 'A guardar...',
    'provider.previewPublicProfile': 'Pré-visualizar Perfil Público',
    'provider.call': 'Ligar',
    'provider.jobDetails': 'Detalhes do Trabalho',
    
    // Providers
    'providers.findProviders': 'Encontrar Prestadores',
    'providers.searchProviders': 'Pesquisar prestadores...',
    'providers.noProvidersFound': 'Ainda não foram encontrados prestadores',
    'providers.checkBackSoon': 'Volte em breve enquanto integramos mais profissionais de limpeza',
    'providers.viewProfile': 'Ver Perfil',
    'providers.bookNow': 'Reservar Agora',
    'providers.newBadge': 'NOVO',
    'providers.verifiedBadge': 'VERIFICADO',
    'providers.findNearYou': 'Encontrar prestadores perto de si...',
    'providers.filterProviders': 'Filtrar Prestadores',
    'providers.narrowSearch': 'Refinar a sua pesquisa',
    'providers.verifiedOnly': 'Apenas Verificados',
    'providers.showVerifiedOnly': 'Mostrar apenas prestadores verificados',
    'providers.minimumRating': 'Classificação Mínima',
    'providers.whereNeedService': 'Onde precisa do serviço?',
    'providers.enterCity': 'Introduza a sua cidade',
    'providers.checkAvailability': 'Verificar Disponibilidade',
    'providers.filterByDate': 'Filtrar por disponibilidade numa data específica',
    'providers.resetFilters': 'Limpar Filtros',
    'providers.activeFilters': 'Filtros ativos:',
    'providers.verified': 'Verificado',
    'providers.stars': 'estrelas',
    'providers.area': 'Área:',
    'providers.date': 'Data:',
    'providers.noMatches': 'Ainda sem correspondências',
    'providers.tryDifferentFilters': 'Experimente filtros diferentes ou expanda a sua área de pesquisa',
    'providers.providersAvailable': 'prestadores disponíveis',
    'providers.provider': 'prestador',
    
    // Addresses
    'addresses.myAddresses': 'As Minhas Moradas',
    'addresses.manageAddresses': 'Gerir até 5 moradas',
    'addresses.addAddress': 'Adicionar Morada',
    'addresses.editAddress': 'Editar Morada',
    'addresses.addNewAddress': 'Adicionar Nova Morada',
    'addresses.addressLabel': 'Etiqueta da Morada',
    'addresses.labelPlaceholder': 'Casa, Escritório, etc.',
    'addresses.firstName': 'Primeiro Nome',
    'addresses.lastName': 'Último Nome',
    'addresses.phone': 'Telefone',
    'addresses.email': 'Email',
    'addresses.country': 'País',
    'addresses.propertyType': 'Tipo de Propriedade',
    'addresses.apartment': 'Apartamento',
    'addresses.house': 'Casa',
    'addresses.layoutType': 'Tipo de Disposição',
    'addresses.studio': 'Estúdio',
    'addresses.oneBedroom': '1 Quarto',
    'addresses.twoBedrooms': '2 Quartos',
    'addresses.threeBedrooms': '3 Quartos',
    'addresses.fourBedrooms': '4 Quartos',
    'addresses.rua': 'Rua',
    'addresses.codigoPostal': 'Código Postal',
    'addresses.portaAndar': 'Porta/Andar',
    'addresses.localidade': 'Localidade',
    'addresses.distrito': 'Distrito',
    'addresses.streetAddress': 'Morada',
    'addresses.aptUnit': 'Apt/Unidade',
    'addresses.postalCode': 'Código Postal',
    'addresses.city': 'Cidade',
    'addresses.province': 'Província',
    'addresses.setPrimary': 'Definir como morada principal',
    'addresses.updateAddress': 'Atualizar Morada',
    'addresses.saveAddress': 'Guardar Morada',
    'addresses.noAddresses': 'Ainda não foram guardadas moradas',
    'addresses.addFirstAddress': 'Adicionar a Sua Primeira Morada',
    'addresses.primary': 'Principal',
    'addresses.deleteAddress': 'Eliminar',
    'addresses.maxAddresses': 'Máximo de 5 moradas permitido',
    'addresses.addressAdded': 'Morada adicionada com sucesso',
    'addresses.addressUpdated': 'Morada atualizada com sucesso',
    'addresses.addressDeleted': 'Morada eliminada',
    'addresses.failedToLoad': 'Falha ao carregar moradas',
    'addresses.failedToSave': 'Falha ao guardar morada',
    'addresses.failedToDelete': 'Falha ao eliminar morada',
    'addresses.confirmDelete': 'Tem a certeza que deseja eliminar esta morada?',
    
    // Bookings
    'bookings.myBookings': 'As Minhas Reservas',
    'bookings.active': 'Ativo',
    'bookings.completed': 'Concluído',
    'bookings.cancelled': 'Cancelado',
    'bookings.viewDetails': 'Ver Detalhes',
    'bookings.paid': 'Pago',
    'bookings.package': 'Pacote',
    'bookings.total': 'Total',
    'bookings.cancelBooking': 'Cancelar Reserva',
    'bookings.leaveReview': 'Deixar uma Avaliação',
    'bookings.noCompleted': 'Sem reservas concluídas',
    'bookings.noCancelled': 'Sem reservas canceladas',
    'bookings.confirmCancel': 'Tem a certeza que deseja cancelar esta reserva?',
    'bookings.bookingCancelled': 'Reserva cancelada',
    'bookings.failedToCancel': 'Falha ao cancelar reserva',
    'bookings.failedToLoad': 'Falha ao carregar reservas',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'pt') ? saved : 'en';
  });

  useEffect(() => {
    const loadUserLanguage = async () => {
      try {
        const { data: { user } } = await supabase.auth.getUser();
        
        if (user) {
          const { data: profile } = await supabase
            .from('profiles')
            .select('language')
            .eq('id', user.id)
            .single();

          if (profile?.language && (profile.language === 'en' || profile.language === 'pt')) {
            setLanguageState(profile.language);
            localStorage.setItem('language', profile.language);
          }
        }
      } catch (error) {
        console.error('Error loading user language:', error);
      }
    };

    loadUserLanguage();
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = async (lang: Language) => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      
      if (user) {
        await supabase
          .from('profiles')
          .update({ language: lang })
          .eq('id', user.id);
      }
      
      setLanguageState(lang);
      localStorage.setItem('language', lang);
    } catch (error) {
      console.error('Error setting language:', error);
      setLanguageState(lang);
      localStorage.setItem('language', lang);
    }
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
